# Generated by Django 2.0.2 on 2019-04-05 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0003_auto_20190405_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='details',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
