# Generated by Django 2.0.2 on 2019-04-05 20:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0004_package_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='price',
        ),
    ]
