# Generated by Django 2.0.2 on 2019-08-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0005_remove_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='photo_main',
            field=models.ImageField(upload_to='nomad/static/photos'),
        ),
    ]
