# Generated by Django 2.0.2 on 2019-08-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0006_auto_20190804_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='photo_main',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
