# Generated by Django 2.0.2 on 2019-08-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20190807_1339'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trip_id',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
