# Generated by Django 2.0.2 on 2019-08-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0007_auto_20190807_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_number', models.URLField(blank=True, db_index=True, max_length=128, unique=True)),
            ],
        ),
    ]
