# Generated by Django 2.0.2 on 2019-08-09 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0008_trip'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='trip_number',
            new_name='url',
        ),
    ]
