# Generated by Django 2.0.2 on 2019-08-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0009_auto_20190809_1335'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Trip',
        ),
        migrations.AddField(
            model_name='package',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=128, unique=True),
        ),
    ]
