# Generated by Django 2.0.2 on 2019-08-09 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0010_auto_20190809_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='url',
            new_name='trip_id',
        ),
    ]
