# Generated by Django 2.0.2 on 2019-08-09 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0012_remove_package_trip_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='trip_id',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
