# Generated by Django 2.2.4 on 2019-08-30 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_photo_main'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(default='', editable=False, upload_to='./photos'),
        ),
    ]
