# Generated by Django 2.2.4 on 2019-08-30 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190830_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='photo_main',
            field=models.ImageField(default='', editable=False, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
