# Generated by Django 2.0.2 on 2019-08-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='details',
            field=models.TextField(max_length=200, null=True),
        ),
    ]
