# Generated by Django 2.0.2 on 2019-08-13 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('details', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(blank=True)),
                ('trip_id', models.URLField(blank=True, db_index=True, max_length=128)),
            ],
        ),
    ]
