# Generated by Django 2.0.2 on 2019-08-13 03:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_highlights', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlights',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='highlights',
            name='list_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
