# Generated by Django 2.0.2 on 2019-08-13 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('city_highlights', '0002_auto_20190813_0338'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Highlights',
            new_name='Highlight',
        ),
    ]
