# Generated by Django 2.0.2 on 2019-08-13 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city_highlights', '0003_auto_20190813_0423'),
    ]

    operations = [
        migrations.AddField(
            model_name='highlight',
            name='slug',
            field=models.SlugField(default=True, max_length=200, unique=True),
        ),
        migrations.AddField(
            model_name='highlight',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
